### ISSUE TITLE
Tooling in its own package?

### ISSUE THREAD

**Issue by coyotte508** [huggingface/huggingface.js#1]
Should we put eslint + prettier config in a package for example?

Also, husky / lint-staged are not configured yet, I didn't research how to properly do it for a mono-repo

**Comment by pngwn** [comment]
> Should we put eslint + prettier config in a package for example?

I wouldn't bother, people expect to find them in the root, there isn't a huge amount of value in hiding them.

> Also, husky / lint-staged are not configured yet, I didn't research how to properly do it for a mono-repo

I'd recommend against tools that can be easily skipped and and get in the way of those making atomic commits (which is a good practice). They also increase friction for contributors. I'd just add a lint action for PRs and leave it at that.

**Comment by o-az** [comment]
> > Should we put eslint + prettier config in a package for example?
> 
> 
> 
> I wouldn't bother, people expect to find them in the root, there isn't a huge amount of value in hiding them.
> 
> 
> 
> > Also, husky / lint-staged are not configured yet, I didn't research how to properly do it for a mono-repo
> 
> 
> 
> I'd recommend against tools that can be easily skipped and and get in the way of those making atomic commits (which is a good practice). They also increase friction for contributors. I'd just add a lint action for PRs and leave it at that.

One benefit of having shared config is extensibility. Looking at popular projects as an example: SveliteKit https://github.com/sveltejs/svelte/blob/master/src/runtime/tsconfig.json

They have a base tsconfig in root and extend it in individual tsconfigs. The compiler configs are overridden as needed.

Same benefit applies to eslint and prettier (shared config).

**Comment by pngwn** [comment]
That doesn't require a tooling package though. You just stick everything in root then individual packages can tweak what they need to.

**Comment by o-az** [comment]
That's true, I'm on the same page - a benefit of putting configs in own packages (eg, extensibility) can be achieved w/o packages.

**Comment by coyotte508** [comment]
Looking into shared eslint config (without package)
