### ISSUE TITLE
Can't see htrflow libary on the hub

### ISSUE THREAD

**Issue by Borg93** [huggingface/huggingface.js#1019]
Hi! 

We did the #1008 pull request last week. 

I can't still see the libarya and snippet on huggingface, see here:
- https://huggingface.co/Riksarkivet/trocr-base-handwritten-hist-swe-2
- https://huggingface.co/Riksarkivet/satrn_htr

Is this something we can look into? or did i miss something from the addition of the libary.

**Comment by coyotte508** [comment]
Hi @Borg93 

Apologies, things are a bit slow this week. Will move to release early next week

**Comment by coyotte508** [comment]
https://huggingface.co/models?library=htrflow

It's available
