### ISSUE TITLE
Add new M4 Apple Silicons chips to Local Apps and Hardware

### ISSUE THREAD

**Issue by ivanfioravanti** [huggingface/huggingface.js#1020]
Add new M4 Apple Silicons chips to Local Apps and Hardware. It seems that maxed out version of each chip is defined in the dropdown.

**Comment by ivanfioravanti** [comment]
I'm on it, I found data in hardware.ts. I see that in comment it's mentioned that fp16 values are used, but for Apple Silicon I see fp32 has been taken, I will make some tests on M4 Max later and update file 🚀

**Comment by julien-c** [comment]
yes, would be awesome to add them! (i think M4 Max ~= 18.4 Tflops)

**Comment by starkdmi** [comment]
#1044
