### ISSUE TITLE
Update peft code snippet

### ISSUE THREAD

**Issue by not-lain** [huggingface/huggingface.js#1047]
The peft code snippet loads a `PeftConfig` parameter which is not used anywhere, I think it would be better to remove that since the entire script functions without it.
cc @BenjaminBossan if you have any inputs about this.
<hr>

![image](https://github.com/user-attachments/assets/3e1ba5ad-0ccb-44ae-878e-f4e852573b37)
<hr>

![image](https://github.com/user-attachments/assets/dc04a46d-0c84-4f7e-919b-033dea950928)

**Comment by BenjaminBossan** [comment]
Yes, I agree, it's not necessary as `PeftModel.from_pretrained` loads the config automatically. Are you interested in creating a PR to remove this line @not-lain?
