### ISSUE TITLE
Support more URLs in commit call

### ISSUE THREAD

**Issue by coyotte508** [huggingface/huggingface.js#109]
Maybe we should then rename `LazyBlob` to `FileBlob` or `LazyFileBlob`? And create `WebBlob`?

That way we'll truly be able to support `URL` in addition to `Blob`. We already do support it but only on node for local files, given the typings are the same on node & browser we should support it on the frontend as well.

There's a real use case here in the demo by @julien-c : https://huggingface.co/spaces/huggingfacejs/push-model-from-web/blob/e0d4ec039a9540dc9aa9fbdffc68d76c5cb2e38c/app.ts#L65

We can use `HEAD` and the `Range` header to be smart about this.

**Comment by Aschen** [comment]
I can give it a try :+1: 

In case the `Range` header is not supported, should I just download the whole file and use a standard `Blob` ?

**Comment by coyotte508** [comment]
> I can give it a try +1
> 
> In case the `Range` header is not supported, should I just download the whole file and use a standard `Blob` ?

Good question... I guess a v1 we can do it rough and maybe optimize somehow in a v2 (to prevent downloading the same file multiple times).

> 3\. The `WebBlob.stream` method may be tricky to implements because we need to return a promise (`fetch` expose a stream in `response.body` but the promise need to resolve first

Maybe you can create a `TransformStream`, and pipe the response to the `writable` part while returning immediately the `readable` part.

**Comment by Aschen** [comment]
> Good question... I guess a v1 we can do it rough and maybe optimize somehow in a v2 (to prevent downloading the same file multiple times).

I don't see why it would be downloaded multiple time unless the action (like click the upload button) is repeated :thinking: (and in this case I think we should re-download) 

> Maybe you can create a TransformStream, and pipe the response to the writable part while returning immediately the readable part.

Unfortunately to access any kind of stream, first an HTTP request should be done and the response awaited. I don't see how it whould be possible to create a stream directly from an URL. (See [here](https://github.com/huggingface/huggingface.js/pull/111/files#diff-d0e720e070055b4f1a7b7ab7dcf160050ddb229ba4bc3ef56965c85f9b18afedR59))

**Comment by Aschen** [comment]
> Something like this? With a way to emit error as well if the fetch fails

Thanks for the hint, I will try something like that (good workshop on stream those features :D )
