### ISSUE TITLE
Committing HF LFS files with URL fails inside browser

### ISSUE THREAD

**Issue by coyotte508** [huggingface/huggingface.js#123]
Added a failing test here: https://github.com/huggingface/huggingface.js/commit/d0991eb353246a3323337ef9bd1d676e2e691679

It uploads an empty file instead. 

The test works in node.

**Comment by coyotte508** [comment]
It seems to compute sha just fine btw, so problem is probably on upload.

Should investigate, and if the browsers are only happy with native blobs, we should maybe during the upload use something like `fetch` with `duplex: 'half'` + streaming request: https://developer.chrome.com/articles/fetch-streaming-requests/#streaming-request-bodies

Should also check for non-LFS files, eg a text file of 8MB, if it works fine or not.

**Comment by Aschen** [comment]
@coyotte508 Which error are you talking about:
 - wrong size header `expected +0 to equal 4194304`
 - wrong header `expected 'text/plain' to be 'text/plain;charset=utf-8' `
 
Is there anything I can do or are they both related to CORS issue in Moon side?

(CF https://github.com/huggingface/huggingface.js/actions/runs/4564221641/jobs/8053715355)

**Comment by coyotte508** [comment]
The CORS error was unrelated to the LFS files upload in the end (only the regular file upload I guess) but it's fixed as well.

It's fixed in https://github.com/huggingface/huggingface.js/commit/a30183882a2efc3db505aa6140144231f871126a

Unfortunately we can't do `fetch(..., {body: webBlob}` in browsers (tried chrome & FF) it seems

**Comment by Aschen** [comment]
FYI, I opened issues in Firefox and Chromium bug trackers to understand why it's not working with `fetch` body
https://bugzilla.mozilla.org/show_bug.cgi?id=1826243
https://bugs.chromium.org/p/chromium/issues/detail?id=1430298
