### ISSUE TITLE
Fix inference browser tests

### ISSUE THREAD

**Issue by coyotte508** [huggingface/huggingface.js#134]
They are broken. They show up green but in fact do not run.

We should look into it, and if no other solution maybe run a mock server instead of overriding fetch

**Comment by Aschen** [comment]
Is it all of them or just those using local files? 

When we started to test inside the browser, we had to omit those test https://github.com/huggingface/huggingface.js/blob/main/packages/inference/test/HfInference.spec.ts#L282

**Comment by coyotte508** [comment]
All of them I think

For example hub tests work: https://github.com/huggingface/huggingface.js/actions/runs/4608445817/jobs/8144210478

Inference tests show empty: https://github.com/huggingface/huggingface.js/actions/runs/4641936795/jobs/8215375567

**Comment by coyotte508** [comment]
Regarding tests using local files, @vvmnnnkv found a workaround in https://github.com/huggingface/huggingface.js/pull/131

**Comment by vvmnnnkv** [comment]
Tried to bump vitest version in #131 and this helped:
https://github.com/huggingface/huggingface.js/actions/runs/4675046263/jobs/8279768410?pr=131

**Comment by coyotte508** [comment]
nice!
