### ISSUE TITLE
Document request and streamingRequest

### ISSUE THREAD

**Issue by coyotte508** [huggingface/huggingface.js#142]
cc @philschmid 

Mainly add them to the README.md for the inference package, add doc string too

Will be needed for inference endpoints, as a lot of customers have their own custom responses

Also the arguments: `args: Args & { data?: Blob | ArrayBuffer }` should probably be `args: Args & ({ data: Blob | ArrayBuffer } | { inputs: unknown })`

**Comment by radames** [comment]
nice, I think that cover that other case for custom pipelines as well using our API inference, one can write a custom `pipeline.py` for example https://huggingface.co/templates/feature-extraction , and the inputs and outputs are unknown, for example I want to build a feature extraction from a binary image, this is not currently cover case on any tasks.

`def __call__(self, inputs: "Image.Image") -> List[float]:`

**Comment by radames** [comment]
very cool, here is an example

```
await hf.request(
  {
    model: "radames/blip_image_embeddings",
    inputs: base64img
  },
  { blob: false, binary: false, wait_for_model: true }
)
```
