### ISSUE TITLE
Allow using custom `fetch`

### ISSUE THREAD

**Issue by coyotte508** [huggingface/huggingface.js#155]
So client can add custom headers, or use sveltekit's fetch, or even run it in node 14

**Comment by coyotte508** [comment]
Add an optional `fetch` param, and if present we'll use that function to do http calls instead of the native `fetch`.

**Comment by coyotte508** [comment]
eg `inference.textGeneration({model: "gpt2", inputs: "..."}, {fetch: isoFetch})` for `@huggingface/inference` or `createRepo({..., fetch: isoFetch})` for `@huggingface/hub`

**Comment by syedMohib44** [comment]
> Add an optional `fetch` param, and if present we'll use that function to do http calls instead of the native `fetch`.

Ohhh alright got it now so no new function I was creating new fetch function from scratch using http glad asked 😆 Thanks man on it! 👍

**Comment by syedMohib44** [comment]
> textGeneration

Ok ok got it now Thanks

**Comment by jimmywarting** [comment]
i don't think there will be necessary to have a custom fetch if undici or node-fetch can recordnize them as being spec compliant. it dose more or less duck typing check rather then doing instance of checks

but it need to have a `symbol.toStringTag` then also
