### ISSUE TITLE
Image-to-Image 

### ISSUE THREAD

**Issue by radames** [huggingface/huggingface.js#157]
It depends on this PR https://github.com/huggingface/api-inference-community/pull/223

```
        Args:
            inputs (:obj:`str`):
                a string containing some text
            image (:obj:`PIL.Image.Image`):
                a condition image
        Return:
            A :obj:`PIL.Image.Image` with the raw image representation as PIL.
```
```
{"inputs": {
    image: base64image,
    text: "",
}}
```

**Comment by coyotte508** [comment]
It is like the pose/controlnet models, an image as a pose, a text of what we want generated, and the output is the input image adapted to fit the text?

**Comment by coyotte508** [comment]
https://huggingface.co/tasks/image-to-image

It seems some of those models do not have text input, only image to image :thinking: 

Can you clarify what it does? Should we use the same `imageToImage` task for both, or call it `imageToImageGuided` instead?

**Comment by osanseviero** [comment]
Internal Slack discussion - https://huggingface.slack.com/archives/C016D661PAN/p1680600898941279?thread_ts=1680599959.804889&cid=C016D661PAN

**Comment by patrickvonplaten** [comment]
In short we have the following type of models in `diffusers`:

- Image2Image ([Stable Diffusion Image2Image](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py), [ControlNet](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_controlnet.py), [Instruct Pix2Pix](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py), [Stable UnCLIP](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_unclip_img2img.py#607)) - all these models have "images" as the main input, called "data-stream" and are additionally **conditioned** on text "condition-stream". => All those models can in theory very well run without text, but just setting the text prompt to: `text=""` . That's what we currently do here: https://github.com/huggingface/api-inference-community/blob/30bf83aef8767406d16a7eb602bc63c8decdf692/docker_images/diffusers/app/pipelines/image_to_image.py#L75 . For ControlNet, there are actually lots of use cases where this makes sense to just provide an image, but for Pix2Pix and SD it  doesn't make too much sense => So for this type it would be great to always have a text and image widget
- Image Variation ([Stable Diff Image variation](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_image_variation.py#L263)) - this is one of the very few pipelines that **only** accepts an image widget where we would have to force the text widget to be empty. However this model isn't really used that much.
