### ISSUE TITLE
GPT4 on huggingface JS?

### ISSUE THREAD

**Issue by hpssjellis** [huggingface/huggingface.js#170]
This huggingface GPT4 access demo is really interesting

https://huggingface.co/spaces/ysharma/ChatGPT4

Can someone perhaps  @coyotte508 @radames suggest how GPT4 access could come with the JS framework?

As you might remember I have a lot of JS single webpage examples of HuggingfaceJS , can I just change the dataset in one of these examples to get GPT4 access or is it not yet available, or does different code need to be used?

My single webpage examples are here:
https://hpssjellis.github.io/my-examples-of-huggingfacejs/public/index.html

Generally they work without a huggingface access token but your limits gets much better if you use a huggingface asses token.

**Comment by coyotte508** [comment]
Hi @hpssjellis 

You can check the source code of the space here: https://huggingface.co/spaces/ysharma/ChatGPT4/blob/main/app.py

They make calls to OpenAPI's url. You can convert their python code to JS if you want to try.

Regarding HF support of Gpt4, it's not available (to my knowledge) for free, see https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g.

See the error message:

> The model anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g is too large to be loaded automatically (52GB > 10GB). For commercial use please use PRO spaces (https://huggingface.co/spaces) or Inference Endpoints (https://huggingface.co/inference-endpoints).

The model is too big for free inference
