### ISSUE TITLE
Add E2E browser tests

### ISSUE THREAD

**Issue by coyotte508** [huggingface/huggingface.js#18]
We have some divering codepaths depending on browser / node, and we only test on node. We should add browser tests.

**Comment by pngwn** [comment]
Can recommend playwright for this purpose: https://playwright.dev/

Very easily to use, very fast and supports multiple browsers, if that is a goal. Also been using for  about a year in the gradio repo and it has been great so far.

**Comment by o-az** [comment]
> Can recommend playwright for this purpose: https://playwright.dev/
> 
> 
> 
> Very easily to use, very fast and supports multiple browsers, if that is a goal. Also been using for  about a year in the gradio repo and it has been great so far.

Can attest, playwright is fantastic

**Comment by coyotte508** [comment]
Ok this is really needed (accidentally [imported `url`](https://github.com/huggingface/huggingface.js/commit/d26b76b769709c93fc778f5459cb3b11bee5e4c7) and broke browser)

**Comment by coyotte508** [comment]
That was easier than expected, just need to run `vitest` with `--browser` and it works!
