### ISSUE TITLE
Model stabilityai/stable-diffusion-2-1 does not exist

### ISSUE THREAD

**Issue by spectraldeviant** [huggingface/huggingface.js#184]
This model has stopped loading via the inference API. Is it just me or is this down indefinitely?

**Comment by radames** [comment]
hi @spectraldeviant , are you trying textToImage task or imageToImage?

I've just tested the textToimage via widget and it's working fine

<img width="668" alt="image" src="https://github.com/huggingface/huggingface.js/assets/102277/955672bf-ddee-45c4-aeb5-92b7cb3783f3">

**Comment by coyotte508** [comment]
There were availability issues with Hugging Face, it's fixed now

**Comment by spectraldeviant** [comment]
text to image. thanks
