### ISSUE TITLE
Decide on single test library to use

### ISSUE THREAD

**Issue by TimMikeladze** [huggingface/huggingface.js#19]
Currently both `mocha` and `jest` are in use.  It would be great to consolidate the testing approach used across all packages.

**Comment by o-az** [comment]
consider https://vitest.dev/ for a much better ride

**Comment by pngwn** [comment]
Can recommend vitest, we are using in on gradio with much success (although we don't test as much as we should). It may also help with some of the browser testing mentioned in #18. 

Happy to help set this up.

**Comment by coyotte508** [comment]
> Can recommend vitest, we are using in on gradio with much success (although we don't test as much as we should). It may also help with some of the browser testing mentioned in #18.
> 
> Happy to help set this up.

Happy to have your help :D

**Comment by o-az** [comment]
@pngwn I'd be more than happy to do the `jest` -> `vitest` switch. Need to make sure first: does that work or have you already started that?

**Comment by pngwn** [comment]
Already started, PR soon.
