### ISSUE TITLE
hf.visualQuestionAnswering is not a function

### ISSUE THREAD

**Issue by codeacme17** [huggingface/huggingface.js#201]
```js
await hf.visualQuestionAnswering({
  model: 'dandelin/vilt-b32-finetuned-vqa',
  inputs: {
    question: 'what the content of this picture',
    image: raw_image,
  },
})
```

I use above code, but there was a error `TypeError: hf.visualQuestionAnswering is not a function`

I found out that `visualQuestionAnswering` doesn't exist on instances of `hf`

**Comment by coyotte508** [comment]
Can you give the full code?

**Comment by vvmnnnkv** [comment]
Please also check inference package version, visualQuestionAnswering appears in v2.2.0

**Comment by codeacme17** [comment]
Yes I updated the version and it solved the problem，THX，I think i can close this issue
