### ISSUE TITLE
Default model selection

### ISSUE THREAD

**Issue by coyotte508** [huggingface/huggingface.js#215]
https://huggingface.co/api/tasks gives default models for various tasks.

We should make `model` optional, and if not specified, use the default model.

We should also maybe create a tasks endpoint in `@huggingface/hub`, but it's a separate issue (we don't want to introduce a dep to `@huggingface/hub` from `@huggingface/inference` at this point I think).

**Comment by vvmnnnkv** [comment]
If it's possible that the default model changes over time and hf.js looks it up dynamically in `/api/tasks`, user's code that doesn't specify the model may suddenly break because of a different model response.
Also, in some tasks the default model doesn't make sense, e.g. tabular regression & classification.

**Comment by coyotte508** [comment]
cc @Wauplin :arrow_up:

**Comment by Wauplin** [comment]
@vvmnnnkv , you are right about the fact that some tasks a default model doesn't make sense for a real use case. It's should be more seen as a way to discover the API itself. This feature is still expected to be useful for popular (and generic) tasks that like text-generation/image-generation, feature extraction, image classification/segmentation,...

About reproducibility, what we do in `huggingface_hub` (the Python client) is to [log a message](https://github.com/huggingface/huggingface_hub/blob/92028da882e47d61703e8c9144028e1ecadab415/src/huggingface_hub/inference/_client.py#L810) to recommend to the user to explicitly set `model=***` as the recommended model might change without prior notice. The goal of having dynamic recommended models is to be able to suggest better models as they come without having to make releases in each client (JS and Python).

In the end, recommended models are mainly made for quick prototyping while we encourage to set models explicitly for more production-ready use cases. Also note that the free Inference API hosted on the Hugging Face Hub is already not really meant to be production-ready or expect high usage.
