### ISSUE TITLE
There's no way to filter models from the hub based on size

### ISSUE THREAD

**Issue by ArsalaBangash** [huggingface/huggingface.js#264]
I was experimenting with the `textGeneration` function and found that some models were too large to be used with the Inference API. 

I was using the Hub API's `listModels` to populate a dropdown of possible models to call, but there was no way of telling if the model was below the 10 GB limit of the Inference API.

I checked the [ApiModelInfo Interface](https://github.com/huggingface/huggingface.js/blob/main/packages/hub/src/types/api/api-model.d.ts) for anything that indicated the size of the model but couldn't find it. 

What do you recommend?

**Comment by ArsalaBangash** [comment]
I see. At the moment, what's the best way for a dev to determine if a model can be called via the default inference API? 

Here are the three cases I've found while browsing: 

1. [Inference available via the Hosted Inference API](https://huggingface.co/tiiuae/falcon-7b-instruct)
2. [Inference API has been turned off for this model.](https://huggingface.co/NousResearch/Llama-2-13b-hf)
3. [Model is supported, but too large to load onto the free Inference API.](https://huggingface.co/adept/fuyu-8b)

**Comment by ArsalaBangash** [comment]
Wonderful! Seems like this is what I was looking for. 

I'll update the issue title to make it more clear and close it.

**Comment by julien-c** [comment]
cool! 

if you build something cool with this, please share it:)
