### ISSUE TITLE
Upgrade Inference Docs

### ISSUE THREAD

**Issue by ArsalaBangash** [huggingface/huggingface.js#274]
## Context

I've been building tutorials and creating demos for the inference library, and I find myself going back and forth between the [JS Library Inference Docs](https://huggingface.co/docs/huggingface.js/inference/README#tree-shaking) and the [Detailed Params documentation](https://huggingface.co/docs/api-inference/detailed_parameters)

## Suggestions

- Split the giant code block into sections for each task.
- Remove the Supported Tasks section and add links to demos in each task's section
- Add links to the Detailed Params docs for each task so devs can easily dig in the params beyond the ones showcased in the code examples
- Add Detailed Params documentation for missing tasks like Audio To Audio, Text To Image, and others.

**Comment by ArsalaBangash** [comment]
I'm open to feedback and suggestions! 

I created a draft PR to help you visualize what I'm going for.

**Comment by radames** [comment]
thanks @ArsalaBangash , this a great idea! thanks for helping improving the docs. I'm happy to review the changes.

**Comment by vvmnnnkv** [comment]
Good stuff, @ArsalaBangash!

Few comments:

> Split the giant code block into sections for each task.
> Remove the Supported Tasks section

I think we should keep task types (CV, NLP, etc.) that previously where comments in the big code block, just make them to be headers not comments. It looks more structured and easier to navigate with them :-)

> Add links to the Detailed Params docs
> Add Detailed Params documentation

It might be confusing that javascript examples provided there are nodejs and plain fetch(), would be nice to have huggingface.js examples as well :-) But as I understand these docs are compiled from private repo https://github.com/huggingface/api-inference not sure if HF allows contributions to that repo. Maybe `docs/` could be split into a public repo @coyotte508?

**Comment by ArsalaBangash** [comment]
@vvmnnnkv I agree with your suggestion of grouping by task type. 

@coyotte508 My 2 cents on converting the api-inference js examples to hf.js: If we have customers who prefer calling the inference API without hf.js, then having those examples is still worth it.

**Comment by ArsalaBangash** [comment]
I committed changes to #275. [Live Preview](https://moon-ci-docs.huggingface.co/docs/huggingface.js/pr_275/en/inference/README)

Before I mark the PR as ready for review, I'd like to clarify:

- Where should TextToImage go? On hf.co/tasks, textToImage is under Multimodal, whereas in this repo, it's under packages/inference/src/tasks/cv
- Why is Table Question Answering categorized as NLP instead of Tabular/Multimodal?

**Comment by ArsalaBangash** [comment]
Docs are live so I'm closing this issue.
