### ISSUE TITLE
Unpredictable 500 errors 

### ISSUE THREAD

**Issue by hypnocill** [huggingface/huggingface.js#278]
I'm using Vercal AI SDK with Hugging Face Inference API and I really like it!

There's one major issue I have though - occasionally the requests will either 'freeze' or result in a 500 error. So far I'm having a hard time finding a pattern or debugging it, it seems to occur randomly and resolves itself randomly. Initially I thought it was some cache locally or due to hot reloading but then I made a preview deploy and test it the next day - it wasn't working and I was getting 500.. then after a few tries, it started working (no idea why and how).

It doesn't seem to be rate limiting because I've made very few requests and because as far as I read, if it were that, it would return a descriptive error.

It's really unpredictable which makes it hard to use and rely on. I'd be really grateful for any help on what the issue might be, how to error handle it and fix it.

Thank you very much!

Here's the error message I get on a preview deploy:

```
Error: Internal Server Error
    at (node_modules/@huggingface/inference/dist/index.mjs:287:14)
    at (node_modules/@huggingface/inference/dist/index.mjs:674:2)
    at (node_modules/ai/dist/index.mjs:478:30)
```

And here's the error locally

```
error Error: Internal Server Error
    at streamingRequest (webpack-internal:///(middleware)/./node_modules/@huggingface/inference/dist/index.mjs:332:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async textGenerationStream (webpack-internal:///(middleware)/./node_modules/@huggingface/inference/dist/index.mjs:668:5)
    at async Object.pull (webpack-internal:///(middleware)/./node_modules/ai/dist/index.mjs:461:37) {
  digest: undefined
}
```

```
import { HfInference } from '@huggingface/inference';
import { verifyAuth } from '@lib/auth';
import { HuggingFaceStream, StreamingTextResponse } from 'ai';
import { NextRequest } from 'next/server';
 
// Create a new Hugging Face Inference instance
const Hf = new HfInference(process.env.HUGGINGFACE_API_KEY);
 
// IMPORTANT! Set the runtime to edge
export const runtime = 'edge';
 
export default async function POST(req: NextRequest) {

  const isAuth = await verifyAuth(req);

  if (!isAuth) {
    throw new Error('Authentication required!');
  }

  const { prompt } = await req.json();

  if (prompt?.length > 100) {
    throw new Error('Prompt too long!');
  } 
 
  const response = await Hf.textGenerationStream({
    model: 'mistralai/Mistral-7B-Instruct-v0.1',
    inputs: `<s>[INST] ${prompt} [/INST] Model answer</s>[INST] Answer in less than 100 words. [/INST]`,
    parameters: {
      max_new_tokens: 140,
      // @ts-ignore (this is a valid parameter specifically in OpenAssistant models)
      typical_p: 0.2,
      repetition_penalty: 1,
      truncate: 1000,
      return_full_text: false,
    },
  });
 
  // Convert the response into a friendly text-stream
  const stream = HuggingFaceStream(response);

  // Respond with the stream
  return new StreamingTextResponse(stream);
}
```

**Comment by julien-c** [comment]
i think @Narsil is OOO so cc @OlivierDehaene too

**Comment by OlivierDehaene** [comment]
Hello @hypnocill,
We have been having some instability issues in the Inference API cluster this week. Basically one service that we use to aggregate Open Telemetry traces was partially un-responsive which led to other components being completetly stuck.
We removed the faulty service today.

Very sorry that it impacted you. Please report back here if this issue happen again.

**Comment by hypnocill** [comment]
Hello @OlivierDehaene and thanks for the response!
I tested the inference API throughout the day today. Earlier, at one point, I was getting 500 errors again occasionally and at other point - very slow responses. At the time I'm writing this, it seems to work perfectly fine. It 'felt' like it gradually improved the more I used it today though it might be just my perception.

Also, is there an example or docs on error handling when the 'textGenerationStream' function is used?  In the code snippet above, I managed to get the errors early on by calling and awaiting in a try/catch the .next() function on the returned AsyncGenerator from textGenerationStream - this works ok for error handling before passing the generator to HuggingFaceStream but if it's a proper response, the first letter of the generated text would be cut out which is bad. Worse case scenario, I could use just the 'textGeneration' function for easier error handling but the user experience would be far from great with it.

I'd love to make it work for my project and eventually deploy the AI assistant feature I'm working on to production.
Thank you for your time and for your work!

**Comment by vvmnnnkv** [comment]
Hi @hypnocill!

> Also, is there an example or docs on error handling when the 'textGenerationStream' function is used? 

I think typically you just wrap `for await` with try/catch block:

```ts
  const response = hf.textGenerationStream({...})
  // ...
  try {
    for await (const token of response) {
      // ...
    }
  } catch (error) {
    // ...
  }
```

If you convert async generator to a stream of some sort (HuggingFaceStream?), you should handle generator's error and propagate it to stream. Then you will be able to handle the stream's error in your code. E.g. if you use node's `Readable.from(async_generator)`, generator's error will be converted to `error` event on stream.

> In the code snippet above, I managed to get the errors early on by calling and awaiting in a try/catch the .next() function on the returned AsyncGenerator from textGenerationStream - 

I think the problem was that the server didn't respond with the error immediately (i.e. status code was 200) but then it returned the error in the first server event. If this is expected API behavior (@OlivierDehaene ?), I think we can check the first server event for error and throw it at the time of `hf.textGenerationStream()` invocation.

**Comment by hypnocill** [comment]
@vvmnnnkv thank you for your response! 

I tested multiple times today and did not get errors. Sometimes it was very fast but often times, the initial response before the stream starts was very slow (up to 30 seconds). Is this an issue or is it expected for the free account's token? 

As for error handling - I experimented with 'for await' but ended up error handling it as follows: 

```
    try {
      await response.next()
    } catch (e) {
      return jsonResponse(500, 'Error occurred')
    }
```
while adding an additional instruction to the model: `Return "AI:" before your answer` so that even though the 'response.next()' removes the first token from the returned stream when there's no error, it will be okay since it will just remove the 'AI' letters. Feels too hacky but does the job and will leave it for now. (though yes, could be more convenient if an error is thrown at the time of hf.textGenerationStream() invocation)

**Comment by OlivierDehaene** [comment]
@hypnocill, the Inference API should not be used for production. We do not provide any SLAs and the model can be unavailable (503 error) at any moment if we need capacity to serve another model.
If the model is not currently being served, it can take up to 30s to start it, consistent with the latency you are reporting.
 
For production use cases where you need to have high availability, I encorage you to look at Huggingface Inference Endpoint or AWS Sagemaker.

**Comment by hypnocill** [comment]
@OlivierDehaene I see, thank you very much!
For the free inference API I read about the rate limiting which seemed okay to me for a start since I don't expect any heavy usage in production where it would be used by very few users. Apparently I've missed the part that it's not for production use, even if it's light use.
I'll take a look at the Inference Endpoints solution and will probably get that and try it out.

Closing the issue now, thank you
