### ISSUE TITLE
Allow generative models with the document QA widget

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface.js#298]
As per recent discussions in https://github.com/huggingface/hub-docs/issues/21, some QA models just return the answer with no score, so it would be good to make the widget more generalizable. The widget does not display the score at all, so it should not be a hard requirement

cc @NielsRogge @mishig25

**Comment by julien-c** [comment]
added https://github.com/huggingface/huggingface.js/labels/good%20first%20issue tag

**Comment by kohsheen1234** [comment]
Hey, can I start working on this issue.

**Comment by osanseviero** [comment]
Of course! You can find the widget at https://github.com/huggingface/huggingface.js/blob/main/packages/widgets/src/lib/components/InferenceWidget/widgets/VisualQuestionAnsweringWidget/VisualQuestionAnsweringWidget.svelte. Feel free to take a stab at it

**Comment by kohsheen1234** [comment]
I tried to replicate the issue with Document QA widget. I observe that score is visible against the answer, would like to confirm what is the expectation here, how should the widget ideally behave.

`Document Question Answer Widget`
<img width="463" alt="Screenshot 2023-11-23 at 5 59 25 PM" src="https://github.com/huggingface/huggingface.js/assets/22408440/eb3fb9dd-3d9f-4d2d-98ec-f0d382ab9e89">

**Comment by kohsheen1234** [comment]
@osanseviero @julien-c I have linked the PR.
Thank you so much for the support :)
