### ISSUE TITLE
Text Classification in Hosted Inference API with Multiple Inputs

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/huggingface.js#310]
Some of the text classification tasks take two inputs just like similarity models, but since the problem is text classification, widget takes only one text, which confuses users on how to pass their text to model in hosted inference API. See [this question in the forum](https://discuss.huggingface.co/t/two-texts-inputs-for-text-classification-in-inference-api/12805). 
Couple of other example models: [Cross Encoder QNLI](https://huggingface.co/cross-encoder/qnli-electra-base) even though these models are based on similarity, they usually return entailment/not entailment
[Cross Encoder MSMARCO Passage Ranking](https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-12-v2) 

Solution is letting user input as many text as they want (like similarity widget) yet keeping the class labels without having an additional pipeline. A similar widget is [zero shot classification](https://api-inference.huggingface.co/docs/python/html/detailed_parameters.html#zero-shot-classification-task) but it takes possible class names and not multiple text input. 

maybe this is relevant for cc: @osanseviero

**Comment by osanseviero** [comment]
Hi all! I'll close this issue as we have not received more requests for this and there are no new models, as far as I know, for this use case. The user in the forum worked around it by creating their own `Pipeline` class.
