### ISSUE TITLE
Tracking integration for Speaker Verification

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/huggingface.js#312]
## Tracking integration of task - Speaker Verification

Note that you're not expected to do all of the following steps. This PR helps track all the steps required to get a new task fully supported in the Hub 🔥

- [ ] Integration with Inference API. Select at least one of the following:
  - [ ] Added a `transformers` `pipeline`
  - [ ] Added to Community Inference API for 3rd party library
  - [ ] Added to Community Inference API for generic
- [ ] Added basic UI elements (icon, order specification, etc)
- [ ] Added a widget

Integration guide: https://hf.co/docs/hub/adding-a-task

Relevant models:
https://huggingface.co/microsoft/wavlm-base-plus-sv

Relevant spaces:
https://huggingface.co/spaces/microsoft/wavlm-speaker-verification (inference API could look like this)

**Comment by osanseviero** [comment]
How do we feel about this issue? We've done this already with `speechbrain` by using `audio-classification` with `speaker-verification` as a subtask (https://github.com/huggingface/hub-docs/blob/main/js/src/lib/interfaces/Types.ts#L350) so I think we can close this.

cc @sanchit-gandhi @Vaibhavs10
