### ISSUE TITLE
Add CODEOWNERS file?

### ISSUE THREAD

**Issue by coyotte508** [huggingface/huggingface.js#331]
eg @nsarrazin for `@huggingface/agents` and @merveenoyan @osanseviero @mishig25 @pcuenca for tasks & widgets

(we can use HF teams as code owners)

https://docs.github.com/fr/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

This would enable the relevant people to be notified for code changes on the related packages without having to watch the whole repo

**Comment by kohsheen1234** [comment]
Hi,
@coyotte508 Can I work on this?

**Comment by kohsheen1234** [comment]
@coyotte508 I have added the file and linked the PR. 🤗

**Comment by julien-c** [comment]
maybe would be simpler/clearer to list actual usernames instead of adding a team indirection, WDYT @coyotte508?
