### ISSUE TITLE
Add check to make sure `@huggingface/tasks` is published _before_ `@huggingface/widgets`

### ISSUE THREAD

**Issue by coyotte508** [huggingface/huggingface.js#361]
We could move to changesets (https://github.com/huggingface/huggingface.js/issues/6, but it was getting complicated esp. with publishing to both github packages & npm)

or add a check in `widgets-publish.yml`, that checks the remote package's checksum against the local one, and error if it doesn't match. (preffered solution IMO) (or even, we could then publish both)

**Comment by kohsheen1234** [comment]
Hey @coyotte508 , can I work on this? :)
