### ISSUE TITLE
improve README.md

### ISSUE THREAD

**Issue by eraygundogmus** [huggingface/huggingface.js#43]
Instead of 

> There are more features of course, check each library's README!

It would be great if we could add some links to other libraries in a table

**Comment by coyotte508** [comment]
The links to the libraries are already at the top of the README

**Comment by eraygundogmus** [comment]
> The links to the libraries are already at the top of the README

Ohh ok. Sorry. But I think there are still improvements here. Do you want me to make a list?

**Comment by coyotte508** [comment]
Sure, you can make a list or a PR!

**Comment by coyotte508** [comment]
Feel free to make a PR, closing this issue since there's nothing particular pointed out.
