### ISSUE TITLE
Publish packages to GPR

### ISSUE THREAD

**Issue by o-az** [huggingface/huggingface.js#47]
Publish npm packages to GitHub Package Registry so people have a choice to install from npm or GPR. Is that something the project would be interested in? I can make a PR.

**Comment by coyotte508** [comment]
Sure!

**Comment by coyotte508** [comment]
(don't mind the labels changes)

**Comment by o-az** [comment]
Should I close this?

**Comment by coyotte508** [comment]
Right, thanks!
