### ISSUE TITLE
Hf-Hub - listModels filter models by library type or custom tag

### ISSUE THREAD

**Issue by phudtran** [huggingface/huggingface.js#497]
Hi, I've been using the listModels from huggingface/hub to search for and download models, and was wondering if there is a way to filter by Libraries, or "Other" custom tags like on [huggingface.co ](huggingface.co/)

<img width="229" alt="image" src="https://github.com/huggingface/huggingface.js/assets/22720475/094f036f-825d-4ba2-8f4d-50f4f47d106a">

<img width="229" alt="image" src="https://github.com/huggingface/huggingface.js/assets/22720475/cd82a49a-8972-466c-868a-7ae40950e291">

**Comment by coyotte508** [comment]
Fixed in `@huggingface/hub@0.14.0`

You can do `listModels({search: {tags: ["gguf", "lora]}})` to search models with both gguf & lora.
