### ISSUE TITLE
Tasks as a pointer in README

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/huggingface.js#51]
[Tasks](https://huggingface.co/tasks) is a project that is built for software developers willing to find appropriate ML model for their use case and build apps, and from what I see in this repository I felt like the audience is somewhat same, does it make sense to put it in README or somewhere in documentation? Wanted to open discussion here before opening a PR.

**Comment by coyotte508** [comment]
Maybe in the @huggingface/inference [README](https://github.com/huggingface/huggingface.js/blob/main/packages/inference/README.md)? cc @TimMikeladze

**Comment by TimMikeladze** [comment]
Agreed.

Not everyone is familiar with the ML space and this repo may be their first exposure to it. 

Providing users with additional helpful links and resources in the  respective readme is a great idea.

**Comment by radames** [comment]
very good idea @merveenoyan, I'll also link add a link to the live doc notebook on Observable.
@merveenoyan do you want to open a PR otherwise I can do it thanks
