### ISSUE TITLE
Page refreshing after clicking `JSON output` while testing `Inference API` of any model

### ISSUE THREAD

**Issue by surjendu104** [huggingface/huggingface.js#513]
I am testing one of the model in HF. While testing `Inference API` after clicking the `Compute` it gives the result. But after that when I click the `JSON output` the page automatically reloads. Take a look

https://github.com/huggingface/huggingface_hub/assets/101238933/528dff55-7751-4f04-bc8e-63ef9d88ce41

To reproduce : Click `JSON output` in any model `Inference API`

**Comment by coyotte508** [comment]
probably a `type="button"` missing in `<button`

**Comment by mishig25** [comment]
The changes should be deployed the next deploy. Will check it & close the issue in the event of success

**Comment by mishig25** [comment]
@surjendu104 the issue is fixed. Thanks a lot for reporting 😃

**Comment by surjendu104** [comment]
cool!! thanks
