### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jedLahrim** [huggingface/huggingface.js#542]
**hey @xenova joshua how you doing ? i wish you're in good shape i have a question about transcriber pipe is the pipeline still transcribe the audio files from this sets:** 

**_https://huggingface.co/datasets/Xenova/transformers.js-docs_**

**or it can be using other links.. inside transcriber() function that take to the audio file inside a storage such as (aws s3, google cloud storage ..)**

**the code**
```
const transcriber = await pipeline('automatic-speech-recognition', 'Xenova/whisper-tiny.en');
const url = 'https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/jfk.wav';
const output = await transcriber(url, { return_timestamps: true });
// {
//   text: " And so my fellow Americans ask not what your country can do for you, ask what you can do for your country."
//   chunks: [
//     { timestamp: [0, 8],  text: " And so my fellow Americans ask not what your country can do for you" }
//     { timestamp: [8, 11], text: " ask what you can do for your country." }
//   ]
// }
```

**Comment by xenova** [comment]
Hi there - this is not the correct GitHub repo for your question. Please reopen in https://github.com/xenova/transformers.js
