### ISSUE TITLE
[Widgets] Log in to compute

### ISSUE THREAD

**Issue by mishig25** [huggingface/huggingface.js#564]
### Feature

Require user to be logged in for compute

| figma1    | figma2 |
| -------- | ------- |
|<img src="https://github.com/huggingface/huggingface.js/assets/11827707/be5e5d35-ea8d-4f3d-b797-5e7f18ddd758">  | <img src="https://github.com/huggingface/huggingface.js/assets/11827707/701bafe4-63da-48a9-b6fa-f7daef8d3543">    |

cc: @julien-c @gary149 @osanseviero @SBrandeis @beurkinger

**Comment by mishig25** [comment]
> (not sure about the 1st mockup actually: in case there are widget examples or cached-API examples we still want to display them no?)

for widgets with examples: maybe we can have "Login to compute" on top of all "compute" buttons

> cached-API examples

for non-logged in users:
1. the widget is interactive/working
2. when they send request, only send the request asking API to return if the example was cached
    a. if the example was cached -> show the output
    b. if the example was not cached -> "Log in to compute" btn appears

**Comment by osanseviero** [comment]
I like it! Maybe we need to make it extra clear it's free?

**Comment by mishig25** [comment]
updated design 

![image](https://github.com/huggingface/huggingface.js/assets/11827707/dc3a701a-da3c-48dd-8e87-a5c5b6726283)
