### ISSUE TITLE
[Widget] Computation device bug

### ISSUE THREAD

**Issue by mishig25** [huggingface/huggingface.js#565]
<img width="259" alt="image" src="https://github.com/huggingface/huggingface.js/assets/11827707/d0a5ac4f-65f9-4646-a978-13d63af24032">

instead of `cpu/gpu`, it is showing `[object Object]`

you can try at: https://huggingface.co/google/gemma-7b

cc: @SBrandeis  @Wauplin @xenova

**Comment by julien-c** [comment]
is this a change from the backend @OlivierDehaene @Narsil?
