### ISSUE TITLE
[gguf types] Add missing types & make existing types stronger

### ISSUE THREAD

**Issue by mishig25** [huggingface/huggingface.js#566]
https://github.com/huggingface/huggingface.js/pull/562 adds initial typing to @huggingface/gguf package.

However, not all architectures are added in #562. (see [here](https://github.com/ggerganov/ggml/blob/master/docs/gguf.md#required) & [here](https://github.com/huggingface/huggingface.js/pull/562#discussion_r1531981246)). For example, one can add [mamba](https://github.com/ggerganov/ggml/blob/master/docs/gguf.md#mamba) & type mamba specific fields (i.e. `mamba.ssm.inner_size`. See RWKV-specific typing for inspiration https://github.com/huggingface/huggingface.js/blob/81e6ce19d119978ce827c3f166d601c8f24fe454/packages/gguf/src/types.ts#L117

**Comment by julien-c** [comment]
if anyone from the comunity wants to take some of this, feel free!
