### ISSUE TITLE
Is 404 console.error expected for `fileExists `

### ISSUE THREAD

**Issue by mishig25** [huggingface/huggingface.js#589]
### Description

When I call `fileExists` on non-existing file, I receive `false`, which is the expected behvaiour. However, I still get console.error "net::ERR_ABORTED 404 (Not Found)" in the browser console (yes, I'm calling it from browser/frontend). Is receiving console.error expected?

https://github.com/huggingface/huggingface.js/blob/f8788fb73fdbda34eb18cc34cf3e4d3ff8795dd9/packages/hub/src/lib/file-exists.ts#L31-L33

### Example

```ts
const hubFileParams = {
	repo: { type: "model", name: "gpt2" },
	hubUrl: "https://huggingface.co",
	path: "model2.safetensors",
};

const res = await fileExists(hubFileParams);

console.log({ res });
```

> HEAD https://huggingface.co/openai-community/gpt2/raw/main/model2.safetensors net::ERR_ABORTED 404 (Not Found)
> {res: false}

cc: @coyotte508

**Comment by julien-c** [comment]
yes i think that's expected. 

I've been tracking a Chromium report / feature request about this for about 12 years

**Comment by mishig25** [comment]
if expected, I'll close the issue

**Comment by julien-c** [comment]
you can still wait for @coyotte508 to chime in maybe

**Comment by coyotte508** [comment]
The only `console.error` for the inference package are in the build script, so it's probably browser-related
