### ISSUE TITLE
Sharded GGUF in subdir

### ISSUE THREAD

**Issue by coyotte508** [huggingface/huggingface.js#592]
> yes valid question from @coyotte508 actually (read too fast initially)
> 
> IIRC @Narsil the `shard index file` contains relative filenames (there's no notion of directory), right? we should always assume the single files are in the same folder imo, correct?

Let's open an issue so we don't forget this, ok?

_Originally posted by @julien-c in https://github.com/huggingface/huggingface.js/issues/563#issuecomment-2012050057_

**Comment by coyotte508** [comment]
cc @mishig25 too

**Comment by julien-c** [comment]
@coyotte508 the issue (and my past comment) is with safetensors files, not GGUF, so i think we can close this one in favor of #588

**Comment by coyotte508** [comment]
yes :facepalm:
