### ISSUE TITLE
[Question] What is the correct way to access commit diff results via http?

### ISSUE THREAD

**Issue by madgetr** [huggingface/huggingface.js#609]
Data I am interested in:
![image](https://github.com/huggingface/huggingface.js/assets/16808224/cada880a-bc46-496b-869b-02adb083b6a7)
Here's the endpoint to list commits
https://huggingface.co/api/models/SimonMA/Codellama-7b-lora-rps-adapter/commits/main

**Comment by julien-c** [comment]
closing given resolved in https://github.com/huggingface/huggingface.js/discussions/608
