### ISSUE TITLE
[ASR Widget] “Browse for file” is unresponsive

### ISSUE THREAD

**Issue by ymoslem** [huggingface/huggingface.js#612]
For automatic speech recognition models like [Whisper](https://huggingface.co/openai/whisper-large-v3), the “Browse for file” button is not responsive. When clicking it, the file navigator opens; however, when selecting an audio file, nothing happens. On the other hand, “Record from browser” works just fine. Also, drag and drop works.

## How to reproduce

* Go to [Whisper](https://huggingface.co/openai/whisper-large-v3) page (or any ASR model)
* Click “Browse for file”
* Browse for an audio file

## Result

I cannot see an error; it seems that the page reloads when the “Browse for file” is clicked. When we select an audio file, its name does not appear on the screen. When we click “Compute”, an error says “You must select or record an audio file” because there is no audio file uploaded.

**Comment by coyotte508** [comment]
Fix works: https://huggingface.co/openai/whisper-large-v3
