### ISSUE TITLE
Inference API widget does not work anymore for token classification of POS

### ISSUE THREAD

**Issue by thibault-roux** [huggingface/huggingface.js#613]
Hey everyone,

I've noticed some troubles with the API inference widget. While it works for NER classification (flair/ner-english-fast, flair/ner-multi, flair/ner-english, etc...), the inference for POS (flair/upos-multi, flair/upos-english-fast, flair/upos-english, etc...) always indicate the same warning:  [No token was detected] 

I mainly checked for Flair models but I haven't found any models where the API inference widget works for POS classification elsewhere.

It should be noted that these models work and the problem is very probably due to a widget update because I remember that they used to work.

Thanks.

**Comment by coyotte508** [comment]
Hi!

@Narsil tried it out:

```
./manager docker flair/upos-english && curl -X POST -d '{"inputs":"I love living in Berlin"}' http://localhost:8000/
```

And gets the same response (empty `[]`)

On https://huggingface.co/flair/upos-english?text=I+love+living+in+Berlin

The model was changed ~1yr ago, maybe that's the reason?

**Comment by Narsil** [comment]
The snippet doesn't work either btw.

**Comment by julien-c** [comment]
@thibault-roux mind opening a discussion directly on the model page? https://huggingface.co/flair/upos-english/discussions

Closing this issue here in the meantime.

Thanks!
