### ISSUE TITLE
How to avoid distributing credential with a web page?

### ISSUE THREAD

**Issue by runvnc** [huggingface/huggingface.js#63]
Hello, if I use this library client-side, how can I do so without giving users my key used to access the API? It seems that I can't prevent that. So then, does the browser API have any use? Node.js support is nice though.

**Comment by coyotte508** [comment]
Yes, it's mentioned: https://github.com/huggingface/huggingface.js/blob/main/packages/inference/README.md#usage

> Note that this API key should be kept private and used exclusively for experimental purposes on the web. If you need to protect it, we suggest setting up a proxy server since we currently do not provide an OAuth solution.

So you need to proxy, or use no token (but then you are rate limited pretty heavily)

**Comment by runvnc** [comment]
Ok, should have read the README. Proxies seem very useful for that.

**Comment by hpssjellis** [comment]
@runvnc @coyotte508. I know this is closed but what is wrong with a text box to enter your token? I have gone the extra step to store it locally even though I know that is not very secure.

[https://hpssjellis.github.io/my-examples-of-huggingfacejs/public/hug04-local-token-storage.html](https://hpssjellis.github.io/my-examples-of-huggingfacejs/public/hug04-local-token-storage.html)
