### ISSUE TITLE
Feature Request: Get Commits List / Commits History by Repository ID using @huggingface/hub

### ISSUE THREAD

**Issue by patrickm68** [huggingface/huggingface.js#646]
### Description:
I'd like to request a new feature in the `@huggingface/hub` package that allows users to retrieve a list of commits associated with a Hugging Face repository using its repository ID. This functionality would be valuable for tracking changes made to a model over time, analyzing its development history, or integrating with other tools that require commit information.

I've looked through the @huggingface/hub documentation but haven't found a function that currently provides this capability.

### Additional Considerations:

It would be great if the returned commit list could include information such as commit hash, author name, commit message, and timestamp.

**Comment by coyotte508** [comment]
Added `listCommits` and `countCommits` to `@huggingface/hub` 0.15.0
