### ISSUE TITLE
Inference CI from forks

### ISSUE THREAD

**Issue by coyotte508** [huggingface/huggingface.js#67]
Forks do not have access to secrets in github actions, so inference tests are rate-limited in the CI.

For now it's fine, but if the rate limit changes or we get more tests it's going to be problematic.

---

Possible solutions:

- Use hard-coded access token from a dummy user for better rate limit, too bad if it's made public
- Use `vitest`'s `--changed` flag to only test what's necessary + split inference source files into many to accomodate it
- ?

Not urgent anyway

**Comment by Aschen** [comment]
@coyotte508 I think you can close this one

**Comment by coyotte508** [comment]
Thanks!
