### ISSUE TITLE
Add a helper to generate Blob (lazily read) from a file path

### ISSUE THREAD

**Issue by coyotte508** [huggingface/huggingface.js#68]
Or wait on https://github.com/nodejs/node/issues/45188

This would help for the `commit` calls, when uploading very large files, to avoid loading the whole file in memory.

Would help with #62 

Technical PR.

---

Given that it's only needed for Deno & Node (and node should have a native solution soon), it should be an internal helper. We want to be able to remove it at some point.

**Comment by coyotte508** [comment]
> Also about the usage `Blob.length` [here](https://github.com/huggingface/huggingface.js/blob/main/packages/hub/src/lib/commit.ts?rgh-link-date=2023-03-17T19%3A54%3A52Z#L218) and [here](https://github.com/huggingface/huggingface.js/blob/main/packages/hub/src/lib/commit.ts?rgh-link-date=2023-03-17T19%3A54%3A52Z#L325), isn't it an error since it does not exists on the Blob API?

Thanks! I added a bug fix: https://github.com/huggingface/huggingface.js/commit/b7934a51c87ab407dca9b28a2c0d6520334a153d

> I started to look into this and if I understood well the problem, I'm thinking about a solution using [Filehandle.read](https://nodejs.org/api/fs.html#filehandlereadbuffer-offset-length-position) but it will need some change in the code because then `slice` method need to be async in order to read the desired slice from the file and returning it in a `Blob` instance.

It should be fine to only do the `Filehandle` calls when `.arrayBuffer()` / `.text()` / `.stream()` is called. As for `.size`, if we pass the info to the new blob when creating it, it should be fine as well.

**Comment by Aschen** [comment]
I suggested a `LazyBlob` implementation here https://github.com/huggingface/huggingface.js/pull/104

Feel free to give me any suggestion
