### ISSUE TITLE
Add Ollama and vLLM as Options for Local Apps in Hugginface

### ISSUE THREAD

**Issue by EliMCosta** [huggingface/huggingface.js#688]
I suggest Ollama and vLLM as options for local apps in Hugginface's model repo because they are two big apps used for dev and prod environments, respectivelly.
![image](https://github.com/huggingface/huggingface.js/assets/87460497/e8cf1278-9892-4608-a2b6-49a901237c57)

**Comment by EliMCosta** [comment]
I've already made some changes to the code, but I don't think they're enough. For example, I couldn't find how to link to each app's icon, which should appear on the Hugginface. Need a feedback/help before a PR:
https://github.com/huggingface/huggingface.js/compare/main...EliMCosta:huggingface.js:patch-1

**Comment by EliMCosta** [comment]
> I've already made some changes to the code, but I don't think they're enough. For example, I couldn't find how to link to each app's icon, which should appear on the Hugginface. Need a feedback/help before a PR: [main...EliMCosta:huggingface.js:patch-1](https://github.com/huggingface/huggingface.js/compare/main...EliMCosta:huggingface.js:patch-1)

Or someone can do the entire PR to solve this issue..

**Comment by julien-c** [comment]
hey, thanks for opening this! indeed, the icons are in our internal codebase – we can take care of those.

Can you split the PR into two and make one just for vLLM?

**Comment by Vaibhavs10** [comment]
re:ollama @EliMCosta - We're thinking about it more closely, we might have some updates soon: https://github.com/huggingface/huggingface.js/pull/687#pullrequestreview-2366815001
