### ISSUE TITLE
Add `text-to-image` API inference 

### ISSUE THREAD

**Issue by radames** [huggingface/huggingface.js#7]
hi @TimMikeladze it would be great to add `text-to-image` on the inference package.
I'm not sure if it's well documented on the [docs](https://huggingface.co/docs/api-inference/detailed_parameters), but it's widely available on all `text-to-image` models widgets on the hub, 
for example https://huggingface.co/prompthero/openjourney?text=mdjrny-v4+style+a+flying+cat

Here a simple example request:
```js
fetch(
  "https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-2",
  {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "X-Wait-For-Model": "true" 
    },
    body: JSON.stringify({
      inputs:
        "award winning high resolution photo of a giant tortoise/((ladybird)) hybrid, [trending on artstation]",
      negative_prompt: "blurry",
    }),
  }
)
  .then((res) => res.blob())
  .then((blob) => {
    const tab = window.open((target = "_blank"));
    tab.location.href = window.URL.createObjectURL(blob);
  });
````

**Comment by TimMikeladze** [comment]
@radames great idea. I sent a PR adding this functionality.

Are there any additional arguments besides `inputs` and `negative_prompt`? I couldn't find anything after a brief look over the documentation.

**Comment by radames** [comment]
hi @TimMikeladze thanks!

Unfortunately, these are the only inputs allowed atm https://github.com/huggingface/api-inference-community/blob/725e38d34ae8c649b63f37da8bcee62622dc8ac1/docker_images/diffusers/app/pipelines/text_to_image.py#L57


We might have other tasks not documented but in the API, wdyt?
https://github.com/huggingface/api-inference-community/blob/6f39af264188099a8929cd2a0148b85c7690b0c4/api_inference_community/validation.py#L211-L241

**Comment by TimMikeladze** [comment]
Below are the tasks which are currently not implemented within the `@hugginface/inference`. I'm creating issues to track each and will see about implementing them in the near-future. 

- [ ] Audio-to-audio 
- [ ] Speech-segmentation
- [ ] Image-to-text
- [ ] Sentence-similarity
- [ ] Tabular-classification
- [ ] Tabular-regression
- [ ] Text-to-speech

**Comment by radames** [comment]
Two more
* [Visual Question Answering](https://huggingface.co/models?pipeline_tag=visual-question-answering)
* [Document Question Answering](https://huggingface.co/models?pipeline_tag=document-question-answering)
