### ISSUE TITLE
Change `accessToken` type to `string`

### ISSUE THREAD

**Issue by o-az** [huggingface/huggingface.js#70]
https://github.com/huggingface/huggingface.js/blob/a1ac81a008b6f5e2244669f2392f01785b69b461/packages/hub/src/types/repo.d.ts#L8

As it is right now if I pass it an environment variable it will complain so the only way is to paste the secret token string directly.

I'm proposing the type be changed to `string` and adding a `checkCredentials` function. I'm thinking something like this: [TS Playground Link](https://www.typescriptlang.org/play?target=99&pretty=true#code/PTAEAsBdIBwZwFwgOYEtLgK4CMB0BjAewFtgBDAGwFMAPAJyrLoBNCA7YSVNgTwFpuANyaoybSAChUxGITqRQXXgEk2wuqPGgAZnRKgAREv5CRYyAYDcEiZB4wqoAMINmVcaIpxQAXlABvUDJ8fCo4OAAVQgBrdwRQOEgNNmRQAF9QEFBpWXlFe0dAlyo3D0pvDN19AHJcTgK4ausJIjZE0ABBAFUIgAkAfQARAHknAGV+roAlABlfQyhYRBAsZDQU7WCqAkJgVnw4YCxsYDgqfEwNOz5IGPc4KxtgACpniVBn0CjYtgTUAC8qPEAMwAdlA+HATGCkCodDg70+33cOjkxDIkHiAANwNp+ljQABqUDAgBMEKhdBhcIRH1AAAEzo5FvAkEdMGtuMhNqEdntCAd2Sczhcrvxbj9ac9gC12O0IsMANIAUQAcv0psqAOLKgAa82AAD1cf0ANpkPj-Dp8ABaAAY+ABOAC6-jJaQAJMBmrRcgptJg2PguOwKedosVSlxygAKfCudzRrzxSOJzxwACU8WwhEI1DEAQkAEhjKp1JpIDH3qAa7XQAAhXP5thxhNlLy4YKhcLItgZgA01brNaxAFlUOEuUEQmFvBL3LhQAAFfNnUDIdxwjGOdiODGgD3+bp9IajCbTGZpLFD0AZ5ol7g8MtmcRVotFhUq9WanW63CwxJWxKNNyk7GcezuPtB3fLFnwoVBmGnbs50gxcV0YNcNzYLdYVAXcggUQ9jwGEZxkmWYr2LO9iwYSBLl+JJMCoaw0ieV5ES+cAUSxSFw1Tds4AJAB3QhMAoRDsEcTAzkQ7g4AQoEOL4UAeIYbcpioWQYwzLFBzpZSeJIYh0G03SlJU3ptFUbQ4XcUJTMRGUJCybQ5FAWgyBkagbF9OQFDIOAeCDHRA2DVBQ3jRhYQ0rSYGhYhEH8G8slwVKb0iqN0xTNsk1pWsUrStIs2XPRjLOAAeQRCAQgA+Qs614-AIxy9MYziqkEoIFrygzZKwFS3AJFYiRfLyAKgvwEKgxDX4iGIYzK3azzEHq-L+rShruuTZwtrymsCsGor4iXUqJyocqxB4Oqkoarimv43K2viuAuuAgTqLSIA)

![CleanShot 2023-03-07 at 21 39 54](https://user-images.githubusercontent.com/23618431/223628819-6ab4909f-e1d7-4caf-b651-4424d00b10f0.png)

```ts
import tinyInvariant from "tiny-invariant"; // [1]

type Credentials = { accessToken: string }; // import type { Credentials } from './types';

const AUTH_DOCS_URL = "https://huggingface.co/docs/hub/security-tokens";

/**
 * Token size: 37 characters
 * Token format: `hf_` + 32 characters
 * @see https://huggingface.co/docs/hub/security-tokens
 */
const TOKEN_REGEX = /^hf_[a-zA-Z0-9]{32}$/;

export function checkCredentials(credentials: Credentials): boolean {
  tinyInvariant(
    Boolean(credentials.accessToken),
    `Missing access token. Please generate one at ${AUTH_DOCS_URL}`
  );

  tinyInvariant(
    TOKEN_REGEX.test(credentials.accessToken),
    `Invalid access token. Please generate one at ${AUTH_DOCS_URL}`
  );
  return true;
}

/**
 * Then `checkCredentials` would be used inside:
 * - `createRepo()`,
 * - `commit()`,
 * - `HfInference()`
 */
```
```ts
import { checkCredentials } from './utilities';
// for example

export async function createRepo(params: {
  // ...
  credentials: Credentials,
  // ...
}): Promise<void> {
  checkCredentials(params.credentials);
  // ...
}

export async function commit(params: {
  // ...
  credentials: Credentials,
  // ...
}): Promise<any> {
  checkCredentials(params.credentials);
}

// ...etc
```
[1] [`tinyInvariant`](https://github.com/alexreardon/tiny-invariant)

**Comment by coyotte508** [comment]
Sure, I guess it's less restrictive. 

Let's not add runtime deps however, we can just do something like this:

```ts
if (credentials?.accessToken !== undefined && !credentials?.accessToken.startsWith("hf_")) {
  throw new TypeError("Invalid access token, it must start with `hf_`");
}
```

**Comment by julien-c** [comment]
yes i guess it's simpler to type it as a string and do runtime validation
