### ISSUE TITLE
Allow `replay.mp4` rendering for robotics tasks

### ISSUE THREAD

**Issue by qgallouedec** [huggingface/huggingface.js#722]
When a model is tagged with `"reinforcement-learning"`, you've get a nice rendering if a file `replay.mp4` is contained in the repo. It would be great to have it also for robotics.
For the moment, we're doing it, but with gifs in README.
Example: https://huggingface.co/lerobot/diffusion_pusht

**Comment by coyotte508** [comment]
cc @osanseviero

**Comment by osanseviero** [comment]
This is now done :fire:

**Comment by qgallouedec** [comment]
Wonderful, thanks!
