### ISSUE TITLE
add Snapdragon X Elite / Plus CPU scores

### ISSUE THREAD

**Issue by sitaoo** [huggingface/huggingface.js#764]
The Snapdragon X Elite / Plus series laptops have been officially released, they come with Qualcomm Adreno GPU and Qualcomm Hexagon NPU, they are very powerful when it comes to running large language models (LLMs).

**Please add the rating to `packages/tasks/src/hardware.ts`**

Reference link:
https://www.qualcomm.com/products/mobile/snapdragon/pcs-and-tablets/snapdragon-x-elite

| Processor              | Qualcomm Oryon CPU |                 |                               |                     | Qualcomm Adreno GPU | Qualcomm Hexagon NPU | Memory          |                   |
| :--------------------- | :----------------- | :-------------- | :---------------------------- | :------------------ | :------------------ | :------------------- | :-------------- | :---------------- |
|                        | **Cores**          | **Total cache** | **Max Multithread frequency** | **Dual core boost** | **TFLOPS**          | **NPU TOPS**         | **Memory Type** | **Transfer Rate** |
| **Snapdragon X Elite** |                    |                 |                               |                     |                     |                      |                 |                   |
| X1E-00-1DE             | 12                 | 42 MB           | 3.8 GHz                       | 4.3 GHz             | 4.6                 | 45                   | LPDDR5x         | 8448 MT/s         |
| X1E-84-100             | 12                 | 42 MB           | 3.8 GHz                       | 4.2 GHz             | 4.6                 | 45                   | LPDDR5x         | 8448 MT/s         |
| X1E-80-100             | 12                 | 42 MB           | 3.4 GHz                       | 4.0 GHz             | 3.8                 | 45                   | LPDDR5x         | 8448 MT/s         |
| X1E-78-100             | 12                 | 42 MB           | 3.4 GHz                       | None                | 3.8                 | 45                   | LPDDR5x         | 8448 MT/s         |
| **Snapdragon X Plus**  |                    |                 |                               |                     |                     |                      |                 |                   |
| X1P-64-100             | 10                 | 42 MB           | 3.4 GHz                       | None                | 3.8                 | 45                   | LPDDR5x         | 8448 MT/s         |

**Comment by coyotte508** [comment]
Hi @sitaoo , thanks for the reference :) 

Feel free to make a PR yourself in https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/src/hardware.ts if you want this to be added faster

**Comment by julien-c** [comment]
adding filter https://github.com/huggingface/huggingface.js/labels/good%20first%20issue

**Comment by Vaibhavs10** [comment]
Closing this issue as addresed in https://github.com/huggingface/huggingface.js/pull/881
