### ISSUE TITLE
count download inactive

### ISSUE THREAD

**Issue by lzy-tony** [huggingface/huggingface.js#771]
Hi. I added a new library (glyph-byt5) to model_libraries.ts in this pr (https://github.com/huggingface/huggingface.js/pull/770). However, the model repo on huggingface still shows that downloads are not being tracked (https://huggingface.co/GlyphByT5/Glyph-SDXL-v2). Could anyone help check it out? Much thanks!

**Comment by coyotte508** [comment]
it takes a few days for changes to propagate to the hub
