### ISSUE TITLE
Enable token streaming for text-generation 

### ISSUE THREAD

**Issue by radames** [huggingface/huggingface.js#78]
We have a few models that already support token streaming. 
We could add an extra options
```
export interface Options { 
	streaming?: boolean;
....
}
```

Here's an example by @julien-c @olivierdehaene using an improved API for [`EventSource`](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) with [`fetch-event-source`](https://github.com/Azure/fetch-event-source). 
https://gist.github.com/julien-c/9565fbc85d0baecee9f910017584d157

Available models

```
[
    "Rallio67/joi2_20B_instruct_alpha",
    "google/flan-t5-xxl",
    "google/flan-ul2",
    "bigscience/bloom",
    "bigscience/bloomz",
    "EleutherAI/gpt-neox-20b"
]
```

**Comment by julien-c** [comment]
_[could be a great first task for Adrien D. who's joining HF on April 10]_
