### ISSUE TITLE
Inference widget for chat models should send example response back

### ISSUE THREAD

**Issue by abidlabs** [huggingface/huggingface.js#780]
In the inference widget for chat models e.g. https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1, we should send the example back, otherwise if a user sends a new message, they'll get this error:

![image](https://github.com/huggingface/huggingface.js/assets/1778297/b44bf865-d2ce-4565-bb9d-4640cd0a04ee)

**Comment by julien-c** [comment]
for @mishig25 maybe?

**Comment by abidlabs** [comment]
It looks like this has been fixed. Thanks @mishig25 and team!

<img width="561" alt="image" src="https://github.com/user-attachments/assets/034afb38-e993-47c9-910c-46637d400515">
