### ISSUE TITLE
[@huggingface/space-header] Allow user to reposition / minimise

### ISSUE THREAD

**Issue by pngwn** [huggingface/huggingface.js#812]
The new space-header is nice but unfortunately if it gets in the way (which it does due to how it is rendered), you have no option but to go back to the embedded space page, which may not be what you want.

We either need a way for the user to move the space header (without leaving the page) or a way to minimise the header further so it becomes small enough to get out of the way.

I want to enable it by default on gradio apps hosted on space but until we have some kind of solution to this we can't really do that as it degrades the experience too much.

**Comment by julien-c** [comment]
do you have a screenshot of what you mean? (bc it's pretty small no?)

**Comment by enzostvs** [comment]
I made a proposal https://github.com/huggingface/huggingface.js/pull/813

**Comment by pngwn** [comment]
The size isnt that important really, it's mainly the fact that it can't be moved. Any size overlay is big enough to block buttons etc on a gradio UI if they land in the right position.
