### ISSUE TITLE
How can I get metadata  such as arch, parameters, quantization, in gguf model?

### ISSUE THREAD

**Issue by hibig** [huggingface/huggingface.js#830]
Alternatively, there is a reliable method to parse file names. I know there is an agreed-upon naming convention.

**Comment by julien-c** [comment]
does the GGUF viewer on the Hub provide you with the info you want? https://huggingface.co/docs/hub/gguf#viewer-for-metadata--tensors-info

**Comment by hibig** [comment]
1. Yes, the information I need is indeed included, but do I have to obtain it through remote host parsing? In my case, I hope to get this information together with the version files.
2. gguf() is blocked by "CORS" in frontend, is  there any implementation in frontend.

**Comment by julien-c** [comment]
This works from the frontend:

```ts
import { gguf } from "@huggingface/gguf";
// remote GGUF file from https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF
const URL_LLAMA = "https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF/resolve/191239b/llama-2-7b-chat.Q2_K.gguf";
const { metadata, tensorInfos } = await gguf(URL_LLAMA);
```

but you need to make sure you input the URL to a specific file (i.e. a URL that contains `resolve`)

**Comment by hibig** [comment]
Thanks!
I really appreciate your help with this problem.
