### ISSUE TITLE
Impossible to enter ISO 639-3 language codes

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/huggingface.js#834]
As reported by @vaishnavsudarshan, the Lushootseed language (`lut`) cannot be entered as a possible language value in the Hub. See:
- https://github.com/huggingface/datasets/issues/7087

This is weird, because the language entry is present in the list. See: https://github.com/huggingface/huggingface.js/blob/98e32f0ed4ee057a596f66a1dec738e5db9643d5/packages/languages/src/languages_iso_639_3.ts#L15186-L15189

I have checked and this issue seems to arise with all other ISO 639-3 language codes as well.

Any idea why?

**Comment by julien-c** [comment]
it's not in the autocomplete (where we only auto-complete ISO 639-1) but they can still input it directly into the markdown editor:

<img width="847" alt="Screenshot 2024-08-05 at 16 23 47" src="https://github.com/user-attachments/assets/b354db00-5b4e-4ce7-8515-21ca9ee696b1">

**Comment by julien-c** [comment]
and in fact there are already valid datasets there: https://huggingface.co/datasets?language=language%3Alut
