### ISSUE TITLE
Loading hub package on browser with importmap doesn't work

### ISSUE THREAD

**Issue by radames** [huggingface/huggingface.js#85]
Trying to run `@huggingface/hub` on the browser adding `hash-wasm` with `importmap` still throws error. Additionally, you can see on the network activity that `hash-wasm` hasn't been loaded. 

Potential solutions, explore `peerDependencies` on package.json ? AFAIK, using rollup you can set https://rollupjs.org/tools/#peer-dependencies and externals, so it doesn't bundle it on the final package. Since jsdelivr is automatically bundling it with rollup, see code transformed [here](https://cdn.jsdelivr.net/npm/@huggingface/hub@0.1.5/+esm)  WDYT?

```
  "peerDependencies": {
    "hash-wasm": "^4.9.0",
  }
```
``` js
<script type="importmap">
      {
        "imports": {
          "@huggingface/hub": "https://cdn.jsdelivr.net/npm/@huggingface/hub/+esm",
          "hash-wasm": "https://cdn.jsdelivr.net/npm/hash-wasm/+esm"
        }
      }
    </script>
    <script type="module">
      import {
        createRepo,
        commit,
        deleteRepo,
        listFiles,
      } from "@huggingface/hub";
</script>

```
To reproduce, you need to upload a file sized > 10MB
https://glitch.com/edit/#!/humble-confirmed-shadow?path=index.htm

<img width="446" alt="image" src="https://user-images.githubusercontent.com/102277/224245012-520fc7c4-1f20-4de1-8529-a919273f8455.png">

**Comment by coyotte508** [comment]
We can add a `tsup` config file:

```
import { defineConfig } from 'tsup'

export default defineConfig({
  noExternal: [
    'hash-wasm'
  ],
  sourcemap: true
})
```

Hopefully it only imports the minimum from `hash-wasm`. 

(Or maybe we can move `hash-wasm` into dev dependencies instead)

**Comment by o-az** [comment]
Tried this locally. It looks like it's loading https://github.com/huggingface/huggingface.js/blob/main/packages/hub/src/utils/sha256-node.ts instead of https://github.com/huggingface/huggingface.js/blob/main/packages/hub/src/utils/sha256.ts?

![Screenshot of Chromium DevTools Console](https://user-images.githubusercontent.com/23618431/224268962-228c7136-4c93-4f69-812f-0670d6634231.png)

**Comment by o-az** [comment]
Slightly relevant: https://nodejs.org/docs/latest-v18.x/api/webcrypto.html#web-crypto-api

I did something like this before for isomorphic `Web Crypto` after encountering a similar issue and searching for a good solution:

```ts
// isomorphic-crypto.ts
export default
  globalThis.crypto ||
  (await import('node:crypto')).default.webcrypto
```
```ts
import crypto from './isomorphic-crypto.ts'
```

Works for both Node and browser env.

**Comment by coyotte508** [comment]
On Node 18, I can access `crypto.subtle` without any flags. Since we also use Node 18 to access `fetch` without any flags, I think it's ok?
