### ISSUE TITLE
Don't display "View Code" in task page widgets

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface.js#863]
For example, when going to https://huggingface.co/tasks/text-to-image , the widget at the right has "View Code" which won't work

cc @Wauplin @merveenoyan @mishig25

**Comment by Wauplin** [comment]
> Don't display "View Code" in task page widgets

Or display `View Code` and make it work (i.e. display code snippet on https://huggingface.co/tasks/text-to-image?inference_api=true)

**Comment by mishig25** [comment]
Uploading Screen Recording 2024-08-29 at 23.36.00.mov…

**Comment by mishig25** [comment]
Fixed by https://github.com/huggingface-internal/moon-landing/pull/10998


https://github.com/user-attachments/assets/6e3e5cc3-c220-4be6-ad52-7f557b0aa819
