### ISSUE TITLE
fix code snippet display for llama-cpp-python 

### ISSUE THREAD

**Issue by not-lain** [huggingface/huggingface.js#865]
https://github.com/huggingface/huggingface.js/pull/840 introduced llama-cpp-python which had some problems in rendering the code snippet (pics below)

![image](https://github.com/user-attachments/assets/6a1db533-4702-4c20-91e6-5ba626a44667)

<hr>

![image](https://github.com/user-attachments/assets/7b9283a6-1b40-4b06-96ec-edd023f0099c)

**Comment by coyotte508** [comment]
Example to repro: https://huggingface.co/google/gemma-2b?library=llama-cpp-python

**Comment by osanseviero** [comment]
FYI I also opened https://github.com/huggingface/huggingface.js/pull/861 but maybe this one is not deployed yet

**Comment by coyotte508** [comment]
Deployed: https://huggingface.co/TheDrummer/Rocinante-12B-v1.1-GGUF?library=llama-cpp-python

**Comment by not-lain** [comment]
thanks for the fix
