### ISSUE TITLE
[@huggingface/hub] add scan_cache_dir capabilities

### ISSUE THREAD

**Issue by axel7083** [huggingface/huggingface.js#905]
The `Hub python library` has the capabilities to scan the caches see https://huggingface.co/docs/huggingface_hub/v0.25.0.rc0/en/package_reference/cache#huggingface_hub.scan_cache_dir

See https://huggingface.co/docs/huggingface_hub/v0.25.0.rc0/en/guides/manage-cache

However, from the JS library, it is impossible to interact with it. (List repositories etc.)

**Comment by julien-c** [comment]
would be a cool issue to tackle!
