### ISSUE TITLE
Fake inference server to mock tests

### ISSUE THREAD

**Issue by coyotte508** [huggingface/huggingface.js#91]
We should run a fake inference server when `env.HF_ACCESS_TOKEN` is undefined.

That way, PRs from works can run tests fine, and we still run real tests on the main repo.

**Comment by Aschen** [comment]
Hello :wave: 

What kind of solution do you have in mind for this?

On my side, I would suggest a [VCR-like](https://github.com/LinkedInAttic/sepia) approach (don't look at the scary `9 years ago`), most likely it would require to:
  - inject the service responsible of the final request (for now it's [fetch](https://github.com/huggingface/huggingface.js/blob/main/packages/inference/src/HfInference.ts#L699)) 
  - decide how to identify an HTTP request (for example `hash(url + verb + body + headers)`)
  - run tests to save answers from HF Inference API in JSON files 
  - commit files and run futur tests with recorded answers in JSON files

**Comment by coyotte508** [comment]
Hey!

In my mind it was to record the responses as you said as a first step. Then run a local server (using express, koa, whichever) that replays those responses depending on the request. The local server can be started / closed in a [globalSetup](https://vitest.dev/config/#globalsetup) file.

Then, in the tests, if HF_ACCESS_TOKEN is defined, call the local server instead. We can add an optional url in the `Options` param for example that can be set to a local server during tests.

**Comment by Aschen** [comment]
I think it would be better to not even use a local server.

For example, we could replace the original `fetch` method to intercept and hash the parameter, do the request with the original fetch and finally save the result in the form of `<hash>.json`

So the next time the same request is executed, the proxy version of `fetch` will first check if a response having the same hash is present.

```js
if (!process.env.HF_ACCESS_TOKEN) {
	const originalFetch = global.fetch;

	global.fetch = (...args) => {
		console.log(args);
		return originalFetch(...args);
	};
}

async function run() {
	await fetch("https://aschen.tech");
}

run();
```

**Comment by coyotte508** [comment]
As long as it works :) 

We should also add a script to regenerate the .json files on command.
