### ISSUE TITLE
text to image arraybuffer to imageData

### ISSUE THREAD

**Issue by hpssjellis** [huggingface/huggingface.js#92]
@coyotte508 @radames any suggestions for converting the text to image arrayBuffer to an imageData object. This does not seem to have the correct dimensions

```

      let UAC = new Uint8ClampedArray( objectDetectionRes, 768, 768);
      let imageData = new ImageData(UAC, 768, 768);

```

**Comment by coyotte508** [comment]
Hi @hpssjellis feel free to use discussions. @TimMikeladze what do you think about returning a `blob` instead from `@huggingface/inference`, it will contain the mime type of the image
