### ISSUE TITLE
[Tasks] Mismatch between input specs and task pipelines expected generation 

### ISSUE THREAD

**Issue by hanouticelina** [huggingface/huggingface.js#923]
# Description
There's a mismatch between the task input spec and the expected generation parameters in task pipelines for automatic-speech-recognition and image-to-text tasks, and possibly others. Specifically, the input schema defines a parameter named [`generate`](https://github.com/huggingface/huggingface.js/blob/9b1ee3a431a01e822d723e02befdbf56a97273b2/packages/tasks/src/tasks/automatic-speech-recognition/spec/input.json#L27) for generation parameters. However, the `_sanitize_parameters()` method implemented in these task pipelines (eg: [AutomaticSpeechRecognitionPipeline. _sanitize_parameters()](https://github.com/huggingface/transformers/blob/be9cf070ee2cb6a9f0d162e5be32d9d68b9df3af/src/transformers/pipelines/automatic_speech_recognition.py#L286))  expects a parameter named `generate_kwargs` instead. 

This mismatch causes errors when calling InferenceAPI according to the specified input specs.

 # Reproduction
If we follow the input specs defined [here](https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/src/tasks/automatic-speech-recognition/spec/input.json) for `automatic-speech-recognition`:
```python
import requests
import base64

API_URL = "https://api-inference.huggingface.co/models/openai/whisper-large-v3"
headers = {"Authorization": f"Bearer {os.environ.get('HF_TOKEN')}"}

with open("sample-3.flac", "rb") as f:
    data = f.read()
payload = {
    "inputs": base64.b64encode(data).decode("utf-8"),
    "parameters": {
        "return_timestamps": True,
        "generate": {
            "max_new_tokens": 100,
            "temperature": 0.7,
        },
    },
}

response = requests.post(
    API_URL,
    headers=headers,
    json=payload,
)
print(response.json())
```
this returns an output with an error:
```
{'error': 'unknown error', 'warnings': ["There was an inference error: unknown error: AutomaticSpeechRecognitionPipeline._sanitize_parameters() got an unexpected keyword argument 'generate'"]}
```
When replacing `generate` with `generate_kwargs`:
```python
import requests
import base64

API_URL = "https://api-inference.huggingface.co/models/openai/whisper-large-v3"
headers = {"Authorization": f"Bearer {os.environ.get('HF_TOKEN')}"}

with open("sample-3.flac", "rb") as f:
    data = f.read()
payload = {
    "inputs": base64.b64encode(data).decode("utf-8"),
    "parameters": {
        "return_timestamps": True,
        "generate_kwargs": {
            "max_new_tokens": 100,
            "temperature": 0.7,
        },
    },
}

response = requests.post(
    API_URL,
    headers=headers,
    json=payload,
)
print(response.json())
```
No error in the output:
```
{'text': ' Thank you.', 'chunks': [{'timestamp': [0.0, 1.0], 'text': ' Thank you.'}]}
```
We have the same issue for `image-to-text` task.

I wanted to open this issue first before proposing any PR to have your opinion first on how to better align the task input specs with the task pipelines.

**Comment by coyotte508** [comment]
To be clear this is a report regarding the  json-schema definitions of tasks in `@huggingface/tasks` in https://github.com/huggingface/huggingface.js/tree/main/packages/tasks/src/tasks/automatic-speech-recognition/spec and such

cc @SBrandeis

**Comment by SBrandeis** [comment]
cc @Wauplin as well

**Comment by Wauplin** [comment]
Thanks for flagging @hanouticelina This is quite annoying indeed. I personally don't like the idea of having an API parameter called `generate_kwargs` (which feels python-centric).

@ArthurZucker @LysandreJik is there a world where `transformers` pipelines could accept either `generate` or `generate_parameters` as kwargs instead of `generate_kwargs`? Since these are used for Inference API and Inference Endpoint, it would be nice to rename them.

**Comment by ArthurZucker** [comment]
`generate_parameters` does not look bad, `generate` is meaningless so no!

**Comment by Wauplin** [comment]
So `generate_parameters` it is then :)

**Comment by Wauplin** [comment]
cc @Rocketknight1 who started to work on integrating officially the specs to `transformers` pipelines in https://github.com/huggingface/transformers/pull/33730.

@hanouticelina let's update the specs to `generate_parameters` and ship it in `huggingface_hub`. Then `transformers` will be able to make the change.

**Comment by hanouticelina** [comment]
Perfect! I will take care of updating the specs now :)

**Comment by pcuenca** [comment]
> `generate_parameters` does not look bad, `generate` is meaningless so no!

Big +1

Or `generation_parameters`, if we are moving away from the Python-centric `generate_kwargs`.

**Comment by pcuenca** [comment]
Exactly my thinking, sorry for not explaining. Thanks @LysandreJik!

**Comment by hanouticelina** [comment]
+1 @pcuenca. It also aligns with the naming used in the schema [here](https://github.com/huggingface/huggingface.js/blob/fae585340d11fb4f7f034387e19e275134e8d882/packages/tasks/src/tasks/common-definitions.json#L27)

**Comment by Wauplin** [comment]
Even better! Agree on `generation_parameters` :)
