### ISSUE TITLE
vLLM Local App Option should only display on GGUF models that are llama.cpp compatible

### ISSUE THREAD

**Issue by simon-mo** [huggingface/huggingface.js#926]
While vLLM does support gguf with models that have the full `config.json` this model is not supported.
https://huggingface.co/kyutai/moshika-candle-q8

**Comment by julien-c** [comment]
@simon-mo I think this could be solved by switching this line https://github.com/huggingface/huggingface.js/blob/cc01ed508cfcc49da56f4a7dd761f18180956692/packages/tasks/src/local-apps.ts#L218

from `isGgufModel` to `isLlamaCppGgufModel`

WDYT?

cc @Vaibhavs10 too

**Comment by julien-c** [comment]
@simon-mo please review @Vaibhavs10's PR^ – or if you want to author the change please open a similar PR! 🙏
