### ISSUE TITLE
Support 'is mapping' as required by llama3.1 Instruct

### ISSUE THREAD

**Issue by mattjcly** [huggingface/huggingface.js#993]
Have run into an issue with huggingface/jinja and [llama3.1 instruct's chat template](https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct/blob/main/tokenizer_config.json#L2053). 

This line from the chat template:
```
{%- if message.content is mapping or message.content is iterable %}
```
Results in error:
```
Unknown test: mapping
```
Have noticed this to be the case with both huggingface/jinja@0.3.0 and huggingface/jinja@0.3.1

Support for this test would be great to avoid the need to patch out this line!

**Comment by coyotte508** [comment]
cc @xenova maybe?
