### ISSUE TITLE
@huggingface/hub: how to use `modelInfo` with proper typing

### ISSUE THREAD

**Issue by axel7083** [huggingface/huggingface.js#996]
THe `modelInfo` method is allowing the caller to define which field will be provided, it has been added in https://github.com/huggingface/huggingface.js/pull/946

https://github.com/huggingface/huggingface.js/blob/186ab738e2f9c7c3613330d45e44848186958815/packages/hub/src/lib/model-info.ts#L9-L11

Here is an example 

```typescript
$: const info = await modelInfo({
	name: "openai-community/gpt2",
});
$: console.log(info);
{
  id: '621ffdc036468d709f17434d',
  name: 'openai-community/gpt2',
  private: false,
  task: 'text-generation',
  downloads: 13764131,
  gated: false,
  likes: 2334,
  updatedAt: 2024-02-19T10:57:45.000Z
}
```

We can ask for additional fields, using the `additionalFields`. Here is an example

```typescript
$: const info = await modelInfo({
	name: "openai-community/gpt2",
        additionalFields: ['author'],
});
$: console.log(info);
{
  // ... omitted 
  author: 'openai-community',
}
```

However I am not able to find proper typing for the method calling and return type.

The return type of `modelInfo` is the following

https://github.com/huggingface/huggingface.js/blob/186ab738e2f9c7c3613330d45e44848186958815/packages/hub/src/lib/model-info.ts#L21

The additionalFields is the following

https://github.com/huggingface/huggingface.js/blob/186ab738e2f9c7c3613330d45e44848186958815/packages/hub/src/lib/model-info.ts#L15

But, I am getting an error when doing the following

```typescript
const info = await modelInfo<'author'>({
	name: "openai-community/gpt2",
	additionalFields: ['author'],
});
```

`TS2344: Type string does not satisfy the constraint never`

I am also interesting in getting the full `ApiModelInfo` object, but I am not able to use the method with the right typing :thinking: .

cc @coyotte508 :)

**Comment by axel7083** [comment]
My solution would be to change the generic type

```diff
- const T extends Exclude<(typeof MODEL_EXPANDABLE_KEYS)[number], (typeof MODEL_EXPANDABLE_KEYS)[number]> = never, 
+ const T extends keyof ApiModelInfo = never,
```

**Comment by coyotte508** [comment]
Thanks for the report!

Releasing version 0.18.3, let us know if there's still issues with some of the fields

**Comment by axel7083** [comment]
Thanks !
